### PR TITLE
standard boilerplate code plus road map

### PR DESCRIPTION
**Pull request by raininja**
After delving into the uport code I've created this request using the standard wordpress boilerplate code generator from wppb.me and added a roadmap.  The trick is going to be twofold:  integrating uport's javascript into the php structure of wordpress and the auth bits.  The usual method would involve using the WP REST API.  Will need discussion.

### CODE REVIEW

**Comment by KamesCG** [comment]
This is exactly the initiative we're looking for @raininja - thank you!

I'm particularly interested in the roadmap you created. Moving forward how would you feel about creating issue/bounty candidates using your roadmap and also implementing the features?

The first library that needs to be converted to PHP is  `did-jwt` (https://github.com/uport-project/did-jwt) which is used to verify credential requests on the Ethereum blockchain. Additionally the `ES256K` and `ES256K-R` would probably also require rewrites in PHP.

I don't know if work has been started on Web3 PHP port, but I imagine something has?

**Comment by raininja** [comment]
You are very welcome! I'm excited about your project, I find it very ingriguing!  

I wouldn't mind at all creating the bounty candidates and implementing them. 

Yes, @KamesCG there are  few implementations of web3 ih php, notably https://github.com/sc0Vu/web3.php and https://github.com/digitaldonkey/ethereum-php.  

Does this mean that I've earned the bounty?

**Comment by raininja** [comment]
OK further research indicates that this is not going to be as complex as I first thought, as infura exists.

**Comment by KamesCG** [comment]
@raininja Great to hear people are already working on the Web3 PHP implementations.

I'm going to follow up Wednesday with a more succinct plan for implementing the uPort Wordpress Plugin.

Infura is fantastic :) we love them!

We are releasing the bounty candidate for https://github.com/uport-project/uport-wordpress-plugin/pull/3 submitted by @tarekskr who claimed the bounty in Gitcoin first.

**Comment by HannahMR** [comment]
Is there an ES256K PHP library yet? I'm considering writing one and want to be sure I'm not duplicating work.

**Pull request closed without merging**
