### PR TITLE
Implement uPort WordPress plugin boilerplate

### PR DESCRIPTION
**Pull request by tarekskr**
Pull request in response to issue #1

### CODE REVIEW

**Comment by KamesCG** [comment]
@tarekskr Would you mind checking to see the difference between your pull request and the one submitted by @raininja?

You have claimed the bounty on Gitcoin and completed the work, so you will be receiving the bounty reward, but I just want to see how much overlap exists or if there is code that can be shared across both pull requests?

https://github.com/uport-project/uport-wordpress-plugin/pull/4

**Comment by tarekskr** [comment]
@KamesCG it's basically the same standard basic structure. I like mine better as it's slightly better formatted but both will work great.

**Comment by raininja** [comment]
Yea its the same basic structure but no road map.  Anyone can go to wppb.me and enter in a few things and get the boilerplate.   That's ok tho, I don't have any ether so I couldn't claim the bounty but whatever.

**Comment by tarekskr** [comment]
@raininja Gitcoin has a faucet here were they could give you initial ether to start with: https://gitcoin.co/faucet

**Comment by raininja** [comment]
Evidently that faucet doesn't work, as I've tried and received nothing.  It's no big deal, I'll just use the time spent to work on the other applicable bounty.

**Comment by tarekskr** [comment]
> Evidently that faucet doesn't work, as I've tried and received nothing.

CC @owocki

**Comment by mkosowsk** [comment]
@raininja sent you a quick tip to get you started as faucet isn't super operational on the weekend :)

**Comment by raininja** [comment]
@mkosowsk thanks! This helps immensely.  The pains of no longer having a desktop machine -_-

**Comment by KamesCG** [comment]
I <3 the Open Source community - thank you @mkosowsk and @owocki 

@raininja You can also expect a tip sent from the uPort team shortly as well. Additionally we're looking forward to continued collaboration.

**Comment by raininja** [comment]
Thanks to @KamesCG @mkosowsk and @owocki  for your generous attention, I'm working to fulfill the second stage towards completion of this plugin.

**Comment by KamesCG** [comment]
@raininja Before we jump into coding the project full steam ahead let's connect. I want ensure time, resources and objectives are in alignment.

Can you join the uPort Community Channel and message me directly?

https://chat.uport.me/

I'm actively working on having a more complete project specification by the end of this week, which will help define the steps for moving forward.

Once again, thank you for the enthusiasm and **get things done** attitude. It's very much appreciated and I think with just a little more planning the repo will be in a place to let the community move full steam ahead.

**Pull request merged**
